server:
  port: 8090

spring:
  # -----------------------------------------
  # spring国际化的使用，用来通过错误码映射得到错误说明
  # -----------------------------------------
  message:
    basename: i18n/ResultCode

  # -----------------------------------------
  # dataSource数据源配置
  # -----------------------------------------
  datasource:
    url: jdbc:mysql://localhost:3306/yanhuohui_goods?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123

# MyBatis mapper.xml路径配置
mybatis:
  mapper-locations: "classpath:mapper/*Mapper.xml"
  type-aliases-package: "com.chenyi.yanhuohui.goods.mapper.*"

  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true







